### PR TITLE
Regular new guns

### PR DESCRIPTION
**Pull request by XviktorwoodX**
these are the last weapons for this year, further, there will be a lull for a month or two. Sorry for loading you with new content.
**USP**
image
_Settings:_
Ammo:basic
Weapon spread: the weapon must be veееееry accurate
Recoil: Small
Damage:5
Max ammo: 12
Sounds: Stock sound is pistol from cgm, silenced is silenced heavy rifle sound
_Attachements:_
Sight
And Silencer (place like this)
image

**AK-74, AK-74M, AKS-74U**
image
image
image
_Settings:_
Like a AKM, but with smaller recoil and more accurate.
_About attachements_
AK-74: only silencer
AK-74M: silencer, grip and sight
AKS-74U: silencer and stock (like a this) 
image

**M16A2**
image
_Settings:_ from M4A1-s but more accurate
_Attachements:_ only silencer

**Kobra**
_Settings:_ like a short sight from cgm
image

Well, its all :)

### CODE REVIEW

**Comment by XviktorwoodX** [comment]
ah stop, 6 damage for usp is so small, 10, better will be 10

**Review by Autovw — COMMENTED** [review]
Thanks for your PR. Models look good to me but I do have one question: Are the 3 AK's meant to be "dyeable" or not? (Because I wasn't able to color them)

**Comment by XviktorwoodX** [comment]
only now I realized that in the current case the USP is ahead of the Deagle in everything, is it possible to raise the Deagle's damage to 14?

**Review by Autovw — COMMENTED** [review]
Still not able to dye the AKS, if this is intended then I'll just merge the PR.

**Comment by XviktorwoodX** [comment]
one sec, ill fix this

**Comment by XviktorwoodX** [comment]
damn, sorry, i just misnamed this file, now test it, i think that this should work

**Review by Autovw — APPROVED** [review]

**Pull request merged**
