### PR TITLE
New guns: M4A1-s and M4A4

### PR DESCRIPTION
**Pull request by XviktorwoodX**
Well, at the moment I have made two weapons, but in the future I think I will make more. I say right away that for m4a1-s you only need to add silencer. On m4a4, you can add sights, grips, as well as silencer
image
image

### CODE REVIEW

**Comment by Autovw** [comment]
I really like the models, but I've got some questions/feedback too.

* The JSON files are very difficult to read, could you please put them through a JSON formatter?
* Which ammo type do you want the guns to use?
* Which sounds do you want the guns to use? (If you want something custom you need to make 'em yourself)
* Also, bear in mind to prevent overlapping parts on the model if possible to prevent z-fighting.

**Comment by XviktorwoodX** [comment]
1. I do not understand what you mean. Optimizing the model? Or something different?
2. Advanced Bullet from MrCrayfish Gun Mod
3. Minigun sounds from MrCrayfish Gun Mod

**Comment by Autovw** [comment]
Just look up "json formatter", it's all on one line (the JSON code) which makes it incredibly hard to read.

**Comment by XviktorwoodX** [comment]
fixed

**Comment by Autovw** [comment]
Is there a reason you closed this PR?
Just let me know here or on Discord if you want me to merge it for you.

**Pull request closed without merging**
